import Head from 'next/head'
import Header from '../components/Header'


export default function Home() {

  const handleClick = () =>{

  }
  return (
    <div className="px-6">
      <Head>
        <title>Instagram 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* Header */}
    <Header/>
     
      
    </div>
  )
}
